project_id = "uywdrexynziahknjnqwd"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-oauth-callback]
verify_jwt = false

[functions.booking-webhook]
verify_jwt = false

[functions.create-staff]
verify_jwt = true